### ISSUE TITLE
Select a branch other than default

### ISSUE THREAD

**Issue by nfgrilo** [askthecode/documentation#7] opened 2023-09-26 09:28 UTC
I'm been testing AskTheCode on my private repo without issues, so that I have subscribed!
However, when I try to access another branch I am unsuccessful:

1. found no way of switching branches on AskTheCode documentation
2. tried with GitHub path like `https://github.com/xxxxx/App/tree/feature/branchXYZ/Modules/MyModuleXPTO`
3. tried with GitHub path like `https://github.com/xxxxx/App/tree/feature/branchXYZ`

On 2. and 3. the responses contained no files (but the files are there), so further analysis is on the default branch (not the desired one)
![image](https://github.com/askthecode/documentation/assets/2744944/cd9588e4-91e0-4e8a-9f3d-a48d0152d3e4)

I insisted that analysis was done on a different branch than the one I specified earlier, but no luck:

![image](https://github.com/askthecode/documentation/assets/2744944/ee621af0-ccfe-4159-b263-5dfef8ae949a)

What's the correct way of selecting a branch for AskTheCode?

Thanks in advance.

**Comment by dsomok** [comment] 2023-09-26 10:58
Hi @nfgrilo,

I can confirm that there is indeed a bug with accessing branches. I've already fixed this issue, and the fix is included in the scope of the next release. I'm currently still testing this release on DEV, especially focusing on stabilizing the new Search feature that will be part of it. I expect to release it tomorrow, or the day after tomorrow in the worst case.

I apologize for the inconvenience this has caused. I'll make sure to notify you in this thread once the release is out.

**Comment by dsomok** [comment] 2023-09-27 19:17
Hi @nfgrilo,

I'm pleased to inform you that the fix for accessing branches has been released. You can find more details about it in the [documentation](https://docs.askthecode.ai/usage/custom-branches/).

P.S. This release also introduces a new cool feature that supports searching within repositories. You can learn more about it in the [documentation](https://docs.askthecode.ai/usage/search/).

**Comment by GitLukeHub** [comment] 2023-09-27 21:37
Hello. I am having the same issue nfgrillo was having. AskTheCode has no problem accessing my main repo branch and the contents inside of it, but is still unable to access other branches inside of it. Even after following the updated method. Thanks.
![Branch Access](https://github.com/askthecode/documentation/assets/25714367/b43f1201-173c-47bb-88d7-68d6d43eeb39)

**Comment by dsomok** [comment] 2023-09-27 22:59
Sorry, it's my fault. All the testing I performed included branches without / in their names.
When you are specifying not just the branch but also a relative path of the repository (for instance, if you want to reduce the scope for the plugin and perform analysis only within a specific directory), the URL looks like:
https://github.com/<owner>/<repo>/tree/<branch>/<relative path>

So, for branches with / inside, only the part prior to the first occurrence of / was considered as the branch name, and the rest was considered as a relative path.

I've just released a hotfix.
Could you please test if it works for you now?

Sorry for the inconvenience. Please ping me if the issue is finally resolved for you.

**Comment by GitLukeHub** [comment] 2023-09-28 00:06
I really appreciate the very timely response. Unfortunately it still does not seem to be working. I tried renaming my branch to see if the / was the issue, with still no luck. The only way it works is if I just direct it to my main repo URL. Could it be something on my end that is the issue? Here are screen shots to provide context. 
![Screenshot 2023-09-27 170114](https://github.com/askthecode/documentation/assets/25714367/23fe63e9-4ef8-4e54-a539-0ad1c772398b)
![Screenshot 2023-09-27 170053](https://github.com/askthecode/documentation/assets/25714367/aa030b7d-0a30-4856-8ade-499b5e07389f)

**Comment by dsomok** [comment] 2023-09-28 10:30
@GitLukeHub thanks for your cooperation and patience :)

I've checked the logs and here is how ChatGPT sends the request to the plugin:
![image](https://github.com/askthecode/documentation/assets/2426834/3a412369-7dca-4545-957a-8cd38fd4ab30)

The problem is that it places your branch as a relative path he wants to query the structure of instead of passing it as a whole repository URL.

Could I please ask you to test my assumption in a new chat window using simple prompt like:
```
https://github.com/GitLukeHub/Galaxia-Repo/tree/v0.3_BasicMultiplayer_04/26/2023
please analyze the repository files and respond with the file names in the root directory
```

The way ChatGPT interacts with the plugin largely depends on the previous conversation and, especially, your prompts, so, it can significantly affect how ChatGPT behaves.

**Comment by nfgrilo** [comment] 2023-09-28 11:07
@dsomok sorry for the late reply, I've missing most of the GitHub notifications 🙃

I just did some tests using a branch with `/` in its name (`/feature/forecasts-v2`) and so far so good! Seems to be working well on my side!

Thanks for your prompt reply and fix 🙏

**Comment by dsomok** [comment] 2023-09-28 12:58
@nfgrilo, thank you for the confirmation, happy to hear that!
In case of any other issues, please do not hesitate to reach out and report an issue.

@GitLukeHub, could you please check once again on your side?

**Comment by GitLukeHub** [comment] 2023-09-28 20:05
Okay, so it didn't work at first, but I figured out the issue. Your suggestion of it depending largely on previous conversations, and prompts made me realize that it could be my custom instructions causing the bug. I deleted my custom instructions of how I wanted ChatGPT to respond to my inquiries in general, and now it seems to be working great. Thank you so much for the fast responses and patience. I will definitely be upgrading to a higher tier of AskTheCode.

**Comment by GitLukeHub** [comment] 2023-09-28 20:22
It might be worth noting this inside the Documentation for other users who might encounter the same issue :)

**Comment by dsomok** [comment] 2023-09-28 20:23
@GitLukeHub, I'm happy to hear that everything is working for you and that you're enjoying using the plugin! I'll be closing this issue as it seems to be resolved. However, please don't hesitate to open new issues if they occur (hopefully not). Thank you for your feedback and cooperation!

**Comment by dsomok** [comment] 2023-09-28 20:25
Yeah, you are absolutely right, I'll update the documentation on how to troubleshoot this feature

**Closed** 2023-09-28 23:49 UTC
